[package]
name = "mica-app"
edition.workspace = true
version.workspace = true
license.workspace = true
description = "Windows shell: Win32 window, input routing, terminal wiring"
authors.workspace = true

[dependencies]
mica-core = { path = "../mica-core" }
mica-render = { path = "../mica-render" }
wgpu = { workspace = true }
anyhow = { workspace = true }

[[bin]]
name = "mica"
path = "src/main.rs"

[build-dependencies]
winres = "0.1"

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Dwm",
    "Win32_System_LibraryLoader",
    "Win32_System_DataExchange",
    "Win32_System_IO",
    "Win32_System_Pipes",
    "Win32_Storage_FileSystem",
    "Win32_UI_Shell",
    "Win32_System_Com",
    "Win32_UI_Shell_Common",
    "Win32_System_Memory",
    "Win32_System_Diagnostics_Debug",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_Ime",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_UI_Accessibility",
    "Win32_System_Ole",
    "Win32_System_Variant",
    "Win32_System_Threading",
] }
windows-core = { workspace = true }
pollster = { workspace = true }
raw-window-handle = { workspace = true }
notify = { workspace = true }
